### PR TITLE
Fixes bug when creating Magnet struct

### PR DESCRIPTION
**Pull request by fliptease**

### CODE REVIEW

**Comment by seaforium** [comment]
Please let me know if I could have done better in creating a pull request or anywhere else.

**Review by gausby — CHANGES_REQUESTED** [review]
Could you please add a test showing the expected behaviour to the test suite ?

This will help the reviewer in verifying the code is correct, as the expected behaviour is shown in the test; and it will make it harder to reintroduce the bug in the future.

**Comment by gausby** [comment]
Hmm, looking into the wikipedia article:

> Magnet URIs can contain multiple parameters, in any order, separated from each other by '&'.
>
> `magnet:? xl = [Size in Bytes] & dn = [file name (URL encoded)] & xt = urn: tree: tiger: [ TTH hash (Base32) ]`

As I read this the `urn:tree:tiger:…` should not get url encoded; and in other places it uses this as an example: `xs=http://192.0.2.27:6346/uri-res/N2R?urn:sha1:FINYVGHENTHSMNDSQQYDNLPONVBZTICF`—the `:`s and `/`s will not fly with my current implementation, as it will URI encode those characters. I think the test suite needs to be improved, and the encoder/decoder need to get reimplemented.

I will help you if you are up for it :)

**Comment by seaforium** [comment]
Sure, it sounds like an interesting exercise. Thanks for the help!

**Comment by seaforium** [comment]
I have a potentially silly question :)

Why not split magnet links by `&` and then `=` using `String.split` in the decoder? I did just that and everything is great but I feel like asking, why did you choose to parse the link character by character instead? Am I missing something?

**Comment by seaforium** [comment]
Ah, I see. You made a good point regarding the length of a link! I didn't think about it but now I see that this method might require more memory due to all the intermediate results.

By the way, what do you think about doing `|> Enum.into(%Magnet{})` right in the `Magnet.decode`? Currently parsing a link is a two-step process, but I have some doubts that providing a keyword list (step 1) is really useful to an end user since a struct (step 2) is easier to get a value from and update.

(Should I continue adding commits to this branch or do I need to create another one and than make a separate pull request?)

**Comment by gausby** [comment]
> By the way, what do you think about doing |> Enum.into(%Magnet{}) right in the Magnet.decode?Currently parsing a link is a two-step process, but I have some doubts that providing a keyword list (step 1) is really useful to an end user since a struct (step 2) is easier to get a value from and update.

I think that sounds like a good idea. I don't know why I made that design decision back in the day :)

**Comment by rustra** [comment]
@seaforium  Looks like this PR could be closed because all concerns were fixed by https://github.com/rustra/magnet/pull/6.

**Pull request closed without merging**
